import { contextBridge, ipcRenderer } from 'electron';
import { IPC_INVOKE_CHANNELS as IPC, IPC_SEND_CHANNELS } from '../shared/ipc-contract';
import type {
  AiQueueEnqueuePreviewArgs,
  ApiResult,
  CaseListExportExcelArgs,
  AiModeBackupDeleteArg,
  AiModeBackupListArg,
  AiModeCandidateReplaceArgs,
  ApplyAiModePartCodeArg,
  RestoreAiModeBackupArg,
  RestoreAiModePartCodeArg,
  ApprovedAiModePartCandidateEntry,
  ExpertApprovedLaborLearningEntry,
  ExpertLearningIdArg,
  ExpertLearningReplaceArgs,
  LaborVehicleContext,
  HasarbotuApi,
  HeavyDamageClearArgs,
  HeavyDamageGenerateNoteArgs,
  HeavyDamageGetArgs,
  HeavyDamagePreviewArgs,
  HeavyDamageSaveArgs,
  KnowledgeImportCommitInput,
  KnowledgeImportDryRunPlanArgs,
  KnowledgeSearchQuery,
  LaborAutoSaveArgs,
  LaborLearningAdminKey,
  LaborLearningUpdateInput,
  LaborDistributeExcelArgs,
  LaborInspectExcelArgs,
  PartsAnalyzePhotoArgs,
  ReportInvoiceComplianceArgs,
  PartsExportLaborArgs,
  PartsLearnTermArgs,
  TrackingAddNoteArgs,
  TrackingAddTodoArgs,
  TrackingDeleteNoteArgs,
  TrackingDeleteTodoArgs,
  TrackingUpdateChecklistArgs,
  TrackingUpdateFieldArgs,
  TrackingUpdateNoteArgs,
  TrackingUpdateTodoArgs,
  TrackingUpdateAiHelperContextArgs,
  TrackingUpdateValueLossContextArgs
} from '../shared/ipc-contract';
import type { AppSettings, ConflictResolutionArgs } from '../shared/types';

const validSendChannels = new Set<string>(IPC_SEND_CHANNELS);

const invoke = <T>(channel: string, ...args: unknown[]) => ipcRenderer.invoke(channel, ...args) as Promise<ApiResult<T>>;

const api: HasarbotuApi = {
  getSettings: <T>() => invoke<T>(IPC.settingsGet),
  saveSettings: <T>(settings: AppSettings) => invoke<T>(IPC.settingsSave, settings),
  chooseRoot: <T>() => invoke<T>(IPC.settingsChooseRoot),
  getDashboard: <T>() => invoke<T>(IPC.dashboardGet),
  listCases: <T>() => invoke<T>(IPC.casesList),
  getCase: <T>(folderPath: string) => invoke<T>(IPC.casesGet, folderPath),
  refreshCase: <T>(folderPath: string) => invoke<T>(IPC.casesRefreshOne, folderPath),
  listFolders: <T>(folderPath?: string) => invoke<T>(IPC.folderList, folderPath),
  scanNow: <T>() => invoke<T>(IPC.scanStart),
  cancelScan: <T>() => invoke<T>(IPC.scanCancel),
  getPhotoThumbnail: <T>(filePath: string) => invoke<T>(IPC.photoGetThumbnail, filePath),
  chooseLaborExcel: <T>() => invoke<T>(IPC.laborChooseExcel),
  inspectLaborExcel: <T>(args: LaborInspectExcelArgs) => invoke<T>(IPC.laborInspectExcel, args),
  distributeLaborExcel: <T>(args: LaborDistributeExcelArgs) => invoke<T>(IPC.laborDistributeExcel, args),
  analyzePartsPhoto: <T>(args?: PartsAnalyzePhotoArgs) => invoke<T>(IPC.partsAnalyzePhoto, args),
  chooseReportInvoicePdf: <T>() => invoke<T>(IPC.reportInvoiceChoosePdf),
  checkReportInvoiceCompliance: <T>(args: ReportInvoiceComplianceArgs) => invoke<T>(IPC.reportInvoiceCompliance, args),
  testReportInvoiceAi: <T>() => invoke<T>(IPC.reportInvoiceTestAi),
  autoLaborPreview: <T>(vehicle?: LaborVehicleContext) => invoke<T>(IPC.laborAutoPreview, vehicle),
  autoLaborSave: <T>(args: LaborAutoSaveArgs) => invoke<T>(IPC.laborAutoSave, args),
  laborLearningList: <T>() => invoke<T>(IPC.laborLearningList),
  laborLearningUpdate: <T>(args: LaborLearningUpdateInput) => invoke<T>(IPC.laborLearningUpdate, args),
  laborLearningDisable: <T>(args: LaborLearningAdminKey) => invoke<T>(IPC.laborLearningDisable, args),
  laborLearningEnable: <T>(args: LaborLearningAdminKey) => invoke<T>(IPC.laborLearningEnable, args),
  laborLearningDelete: <T>(args: LaborLearningAdminKey) => invoke<T>(IPC.laborLearningDelete, args),
  laborLearningExport: <T>() => invoke<T>(IPC.laborLearningExport),
  laborLearningImport: <T>() => invoke<T>(IPC.laborLearningImport),
  expertLearningPreviewExcel: <T>() => invoke<T>(IPC.expertLearningPreviewExcel),
  expertLearningList: <T>() => invoke<T>(IPC.expertLearningList),
  expertLearningApprove: <T>(candidates: ExpertApprovedLaborLearningEntry[]) => invoke<T>(IPC.expertLearningApprove, candidates),
  expertLearningDeactivate: <T>(args: ExpertLearningIdArg) => invoke<T>(IPC.expertLearningDeactivate, args),
  expertLearningReactivate: <T>(args: ExpertLearningIdArg) => invoke<T>(IPC.expertLearningReactivate, args),
  expertLearningReplaceDuplicate: <T>(args: ExpertLearningReplaceArgs) => invoke<T>(IPC.expertLearningReplaceDuplicate, args),
  expertLearningDelete: <T>(args: ExpertLearningIdArg) => invoke<T>(IPC.expertLearningDelete, args),
  aiModePartCandidatesList: <T>() => invoke<T>(IPC.aiModePartCandidatesList),
  aiModePartCandidatesApprove: <T>(candidates: ApprovedAiModePartCandidateEntry[]) => invoke<T>(IPC.aiModePartCandidatesApprove, candidates),
  aiModePartCandidatesDeactivate: <T>(args: ExpertLearningIdArg) => invoke<T>(IPC.aiModePartCandidatesDeactivate, args),
  aiModePartCandidatesReactivate: <T>(args: ExpertLearningIdArg) => invoke<T>(IPC.aiModePartCandidatesReactivate, args),
  aiModePartCandidatesReplaceDuplicate: <T>(args: AiModeCandidateReplaceArgs) => invoke<T>(IPC.aiModePartCandidatesReplaceDuplicate, args),
  aiModePartCandidatesApplyToDColumn: <T>(args: ApplyAiModePartCodeArg) => invoke<T>(IPC.aiModePartCandidatesApplyToDColumn, args),
  aiModePartCandidatesRestoreLastApply: <T>(args: RestoreAiModePartCodeArg) => invoke<T>(IPC.aiModePartCandidatesRestoreLastApply, args),
  aiModePartCandidatesDelete: <T>(args: ExpertLearningIdArg) => invoke<T>(IPC.aiModePartCandidatesDelete, args),
  aiModePartCodeBackupsList: <T>(args: AiModeBackupListArg) => invoke<T>(IPC.aiModePartCodeBackupsList, args),
  aiModePartCodeBackupsDelete: <T>(args: AiModeBackupDeleteArg) => invoke<T>(IPC.aiModePartCodeBackupsDelete, args),
  aiModePartCodeBackupsRestore: <T>(args: RestoreAiModeBackupArg) => invoke<T>(IPC.aiModePartCodeBackupsRestore, args),
  aiModePartCodeHistoryList: <T>() => invoke<T>(IPC.aiModePartCodeHistoryList),
  getAiQueueSnapshot: <T>() => invoke<T>(IPC.aiQueueGetSnapshot),
  getAiQueueEvents: <T>(limit?: number) => invoke<T>(IPC.aiQueueGetEvents, limit),
  getAiQueueTask: <T>(queueTaskId: string) => invoke<T>(IPC.aiQueueGetTask, queueTaskId),
  enqueueAiPreview: <T>(args: AiQueueEnqueuePreviewArgs) => invoke<T>(IPC.aiQueueEnqueuePreview, args),
  cancelAiQueueTask: <T>(queueTaskId: string, reason?: string) => invoke<T>(IPC.aiQueueCancelTask, queueTaskId, reason),
  clearAiQueueFinished: <T>() => invoke<T>(IPC.aiQueueClearFinished),
  searchKnowledge: <T>(query: KnowledgeSearchQuery | string) => invoke<T>(IPC.knowledgeSearch, query),
  listKnowledgeSources: <T>() => invoke<T>(IPC.knowledgeListSources),
  getKnowledgeSource: <T>(sourceId: string) => invoke<T>(IPC.knowledgeGetSource, sourceId),
  getKnowledgeChunk: <T>(chunkId: string) => invoke<T>(IPC.knowledgeGetChunk, chunkId),
  dryRunKnowledgeImportPlan: <T>(args: KnowledgeImportDryRunPlanArgs) => invoke<T>(IPC.knowledgeImportDryRunPlan, args),
  chooseFilesForKnowledgeImportDryRun: <T>() => invoke<T>(IPC.knowledgeImportChooseFilesDryRun),
  previewTextFileForKnowledgeImport: <T>() => invoke<T>(IPC.knowledgeImportPreviewTextFile),
  commitApprovedKnowledgeImportTextPreview: <T>(args: KnowledgeImportCommitInput) => invoke<T>(IPC.knowledgeImportCommitApprovedTextPreview, args),
  heavyDamagePreview: <T>(args: HeavyDamagePreviewArgs) => invoke<T>(IPC.heavyDamagePreview, args),
  heavyDamageGet: <T>(args: HeavyDamageGetArgs) => invoke<T>(IPC.heavyDamageGet, args),
  heavyDamageSave: <T>(args: HeavyDamageSaveArgs) => invoke<T>(IPC.heavyDamageSave, args),
  heavyDamageClear: <T>(args: HeavyDamageClearArgs) => invoke<T>(IPC.heavyDamageClear, args),
  heavyDamageGenerateNote: <T>(args: HeavyDamageGenerateNoteArgs) => invoke<T>(IPC.heavyDamageGenerateNote, args),
  getPartUserTerms: <T>() => invoke<T>(IPC.partsGetUserTerms),
  learnPartTerm: <T>(args: PartsLearnTermArgs) => invoke<T>(IPC.partsLearnTerm, args),
  exportPartsLaborExcel: <T>(args: PartsExportLaborArgs) => invoke<T>(IPC.partsExportLaborExcel, args),
  exportCaseListExcel: <T>(args: CaseListExportExcelArgs) => invoke<T>(IPC.casesExportExcel, args),
  updateChecklist: <T>(args: TrackingUpdateChecklistArgs) => invoke<T>(IPC.trackingUpdateChecklist, args),
  addTodo: <T>(args: TrackingAddTodoArgs) => invoke<T>(IPC.trackingAddTodo, args),
  updateTodo: <T>(args: TrackingUpdateTodoArgs) => invoke<T>(IPC.trackingUpdateTodo, args),
  deleteTodo: <T>(args: TrackingDeleteTodoArgs) => invoke<T>(IPC.trackingDeleteTodo, args),
  addNote: <T>(args: TrackingAddNoteArgs) => invoke<T>(IPC.trackingAddNote, args),
  updateNote: <T>(args: TrackingUpdateNoteArgs) => invoke<T>(IPC.trackingUpdateNote, args),
  deleteNote: <T>(args: TrackingDeleteNoteArgs) => invoke<T>(IPC.trackingDeleteNote, args),
  resolveConflict: <T>(args: ConflictResolutionArgs) => invoke<T>(IPC.trackingResolveConflict, args),
  inspectConflictCopy: <T>(folderPath: string) => invoke<T>(IPC.trackingInspectConflictCopy, folderPath),
  acceptDiskBaseline: <T>(folderPath: string) => invoke<T>(IPC.trackingAcceptDiskBaseline, folderPath),
  updateField: <T>(args: TrackingUpdateFieldArgs) => invoke<T>(IPC.trackingUpdateField, args),
  updateAiHelperContext: <T>(args: TrackingUpdateAiHelperContextArgs) => invoke<T>(IPC.trackingUpdateAiHelperContext, args),
  updateValueLossContext: <T>(args: TrackingUpdateValueLossContextArgs) => invoke<T>(IPC.trackingUpdateValueLossContext, args),
  openFolder: <T>(folderPath: string) => invoke<T>(IPC.systemOpenFolder, folderPath),
  getHealth: <T>() => invoke<T>(IPC.healthGet),
  getDeploymentStatus: <T>() => invoke<T>(IPC.deploymentGetStatus),
  registerDeploymentClient: <T>() => invoke<T>(IPC.deploymentRegisterClient),
  on: (channel: string, callback: (payload: unknown) => void) => {
    if (!validSendChannels.has(channel)) return () => undefined;
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
    ipcRenderer.on(channel, listener);
    return () => ipcRenderer.removeListener(channel, listener);
  }
};

contextBridge.exposeInMainWorld('hasarbotu', api);
